<a href="https://colab.research.google.com/github/solomeya12345-code/python_for_data_analitic/blob/main/Homework_3_4_3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv('drive/MyDrive/Python_for_DA/supermarket_sales.csv')

In [4]:
df[50:55]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
50,326-78-5178,C,Naypyitaw,Member,Male,Food and beverages,91.40,7,31.9900,671.7900,2/3/2019,10:19,Cash,639.80,4.761905,31.9900,9.5
51,162-48-8011,A,Yangon,Member,Female,Food and beverages,44.59,5,11.1475,234.0975,2/10/2019,15:10,Cash,222.95,4.761905,11.1475,8.5
52,616-24-2851,B,Mandalay,Member,Female,Fashion accessories,17.87,4,3.5740,75.0540,3/22/2019,14:42,Ewallet,71.48,4.761905,3.5740,6.5
53,778-71-5554,C,Naypyitaw,Member,Male,Fashion accessories,15.43,1,0.7715,16.2015,1/25/2019,15:46,Credit card,15.43,4.761905,0.7715,6.1
54,242-55-6721,B,Mandalay,Normal,Male,Home and lifestyle,16.16,2,1.6160,33.9360,3/7/2019,11:49,Ewallet,32.32,4.761905,1.6160,6.5

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [4]:
income_by_branches = df.groupby('Branch')['gross income'].sum()
income_by_branches

Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

In [5]:
income_by_branches.sort_values(ascending=False)[:1]

Branch
C    5265.1765
Name: gross income, dtype: float64

Найвищий прибуток в філіалу 'С'.

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [6]:
df.groupby('Branch').agg({'City': 'first', 'gross income': [pd.Series.sum]})

             City gross income
            first          sum
Branch
A          Yangon    5057.1605
B        Mandalay    5057.0320
C       Naypyitaw    5265.1765

#### Альтернативно:

In [7]:
# знаходимо індекс максимального значення (назву філіалу) для фільтрації
max_income_branch = income_by_branches.idxmax()
max_income_branch

'C'

In [8]:
df[['Branch', 'City']].drop_duplicates()

  Branch       City
0      A     Yangon
1      C  Naypyitaw
9      B   Mandalay

In [9]:
city_branch_dict = df[['Branch', 'City']].drop_duplicates().set_index('Branch').to_dict()['City']
city_branch_dict

{'A': 'Yangon', 'C': 'Naypyitaw', 'B': 'Mandalay'}

In [10]:
city_branch_dict[max_income_branch]

'Naypyitaw'

In [11]:
df[df.Branch==max_income_branch].City.unique()

array(['Naypyitaw'], dtype=object)

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [35]:
invoices_by_category = df.pivot_table(index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')

invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

#### Альтернативно:

In [12]:
invoices_by_category = df.pivot_table(index='Branch', columns='Product line', aggfunc='size')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [49]:
invoices_by_category['Electronic accessories'].idxmax()

'A'

#### Альтернативно:

In [14]:
invoices_by_category['Electronic accessories'].sort_values(ascending=False)[:1]

Branch
A    60
Name: Electronic accessories, dtype: int64

In [16]:
# якщо хочете вивести саме назву філії
invoices_by_category['Electronic accessories'].sort_values(ascending=False)[:1].index[0]

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

### - Чи відрізняється кількість покупок в різних категоріях від статі? / Чи впливає місяць на кількість покупок в різних категоріях?

In [5]:
gender_depend = df.pivot_table(index='Gender', columns='Product line', values='Invoice ID', aggfunc='count')

gender_depend

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,84,96,90,64,79,88
Male,86,82,84,88,81,78

In [11]:
def get_month(x):
  month = int(x.split('/')[0])
  if month == 1:
    return 'January'
  elif month == 2:
    return 'February'
  elif month == 3:
    return 'March'
  elif month == 4:
    return 'April'
  elif month == 5:
    return 'May'
  elif month == 6:
    return 'June'
  elif month == 7:
    return 'July'
  elif month == 8:
    return 'August'
  elif month == 9:
    return 'Septmber'
  elif month == 10:
    return 'October'
  elif month == 11:
    return 'November'
  else:
    return 'December'
get_month('12/3/2019')

'December'

In [16]:
month_depend = df.pivot_table(index=df['Date'].apply(get_month), columns='Product line', values='Invoice ID', aggfunc='count')

month_depend

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Date,,,,,,
February,54,60,62,46,38,43
January,54,64,56,49,59,70
March,62,54,56,57,63,53

In [17]:
df['Date'].apply(get_month).unique()

array(['January', 'March', 'February'], dtype=object)

Завдяки даній вибірці можна зробити висновки, що, наприклад, чоловіки більше купляють товари у категорії `Health and beauty`. Можна зробити акцію чи подати товари так, щоб це було цікаво жінкам.

Товари з категорії `Sports and travel` найбільше купляють у січні, можна зробити "Пропозицію місяця" у ті місяці, в яких продажі в даній категорії менші.

### - Чи впливає тип клієнтів на середній чек?
Можна залучати в програму лояльності.

In [22]:
df.groupby('Customer type')['Total'].mean()

Customer type
Member    327.791305
Normal    318.122856
Name: Total, dtype: float64

In [19]:
df.groupby('Customer type')['Invoice ID'].count()

Customer type
Member    501
Normal    499
Name: Invoice ID, dtype: int64

По результату вибірки можемо побачити, що `Member` витрачають більше коштів в середньому в одному чеці. Різниця незначна, але на основі цього можемо зробити висновок, що краще залучати клієнтів в програму лояльності.

### - Який рейтинг в різних філій, та чи впливає це на кількість продажів?

In [29]:
df['Rating'] = df['Rating'].round(0)
sorted(df['Rating'].unique())

[np.float64(4.0),
 np.float64(5.0),
 np.float64(6.0),
 np.float64(7.0),
 np.float64(8.0),
 np.float64(9.0),
 np.float64(10.0)]

In [26]:
branch_rating = df.pivot_table(index='Branch', columns='Rating', values='Invoice ID', aggfunc='count')
branch_rating

Rating  4.0   5.0   6.0   7.0   8.0   9.0   10.0
Branch
A         36    39    60    62    60    50    33
B         37    52    69    48    56    41    29
C         29    42    64    49    63    50    31

In [30]:
df.groupby('Branch')['Rating'].mean()

Branch
A    7.038235
B    6.822289
C    7.064024
Name: Rating, dtype: float64

In [33]:
df.groupby('Branch')['Total'].sum()

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

Бачимо, що середній рейтинг впливає на загальну суму роботи філії. А також небагато покупців дають найвищий рейтинг. Варто зробити опитування для того, щоб визначити, чим саме клієнти незадоволені, і виправити це.

### Нижче приклади запитань до наших даних. "Розв'язок":

**Питання №1**

Визначити найбільш та найменш популярні категорії продукції сумарно по всіх магазинах та середню вартість придбаних товарів, без урахування податку по кожній категорії.

In [17]:
#Розраховуємо загальну кількість відвідувань по всім категоріям по всіх магазинах
most_popular_product_line = df.groupby('Product line').agg({'Invoice ID':'count'})

#Розраховуємо середню вартість придбаних товарів по кожній категорії
cogs_mean_rer_product_line = df.groupby('Product line').cogs.mean()
display(most_popular_product_line)

with pd.option_context("display.precision", 2):
    display(cogs_mean_rer_product_line)

                        Invoice ID
Product line
Electronic accessories         170
Fashion accessories            178
Food and beverages             174
Health and beauty              152
Home and lifestyle             160
Sports and travel              166

Product line
Electronic accessories    304.41
Fashion accessories       290.56
Food and beverages        307.31
Health and beauty         308.23
Home and lifestyle        320.61
Sports and travel         316.25
Name: cogs, dtype: float64

**Питання 2**

Як відрізняється кількість здійснених покупок по всім категоріям в розрізі гендера покупця.

In [18]:
# Таблиця з кількістю інвойсів по категоріям товарів для жінок і чоловіків
invoices_by_product_line_and_gender = df.pivot_table(index=['Gender'], columns=['Product line'], values=['Invoice ID'], aggfunc='count')
display(invoices_by_product_line_and_gender)

# Відображаємо різницю між кількістю інвойсів в сусідніх категоріях товарів
display(invoices_by_product_line_and_gender.diff(1))

                         Invoice ID                                         \
Product line Electronic accessories Fashion accessories Food and beverages
Gender
Female                           84                  96                 90
Male                             86                  82                 84


Product line Health and beauty Home and lifestyle Sports and travel
Gender
Female                      64                 79                88
Male                        88                 81                78

                         Invoice ID                                         \
Product line Electronic accessories Fashion accessories Food and beverages
Gender
Female                          NaN                 NaN                NaN
Male                            2.0               -14.0               -6.0


Product line Health and beauty Home and lifestyle Sports and travel
Gender
Female                     NaN                NaN               NaN
Male                      24.0                2.0             -10.0

**Питання 3**

Визначити найпопулярніший спосіб оплати, а також загальну суму, на яку придбано товарів з різними способами оплати.

In [19]:
df.Payment.value_counts()

Payment
Ewallet        345
Cash           344
Credit card    311
Name: count, dtype: int64

In [20]:
df.groupby('Payment').cogs.sum()

Payment
Cash           106863.40
Credit card     95968.64
Ewallet        104755.34
Name: cogs, dtype: float64

In [25]:
def get_hour(x):
  return int(x.split(':')[0])

In [26]:
df['Hour'] = df.Time.apply(get_hour)

In [27]:
# Конвертуємо колонку 'Date' у формат datetime
df['Date'] = pd.to_datetime(df['Date'])

# Додаємо нову колонку 'Day_of_Week', яка містить день тижня
df['Day_of_Week'] = df['Date'].dt.day_name()

# Групування даних за днем тижня та часом
sales_by_day_time = df.groupby(['Day_of_Week', 'Hour'])['gross income'].sum()

In [28]:
display(sales_by_day_time)

Day_of_Week  Hour
Friday       10      270.0805
             11      126.1565
             12      102.8210
             13      324.9670
             14      246.0130
                       ...
Wednesday    16      153.7915
             17      147.6795
             18      201.6080
             19      198.1035
             20      132.5160
Name: gross income, Length: 77, dtype: float64

In [29]:
# Знаходимо годину з максимальним прибутком для кожного дня тижня
max_sales_by_day_time = sales_by_day_time.groupby(level='Day_of_Week').idxmax()

print(max_sales_by_day_time)

Day_of_Week
Friday          (Friday, 13)
Monday          (Monday, 15)
Saturday      (Saturday, 19)
Sunday          (Sunday, 19)
Thursday      (Thursday, 10)
Tuesday        (Tuesday, 19)
Wednesday    (Wednesday, 13)
Name: gross income, dtype: object